name: Build & Release

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * 0'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      build_date: ${{ steps.ts.outputs.DATE }}
      timestamp: ${{ steps.ts.outputs.TIME }}
      fancy_date: ${{ steps.ts.outputs.FANCYDATE }}
      build_type: ${{ steps.ts.outputs.KERNEL_BUILD_TYPE }}
    steps:
      - id: ts
        run: |
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
          echo "TIME=$(date +'%s')" >> $GITHUB_OUTPUT
          echo "FANCYDATE=$(date +'%Y/%m/%d')" >> $GITHUB_OUTPUT
          echo "KERNEL_BUILD_TYPE=Release" >> $GITHUB_OUTPUT
  
  # device workflow imports
  build-lineage-sm6150:
    needs: setup
    uses: ./.github/workflows/lineage-sm6150.yml
    with:
      build_date: ${{ needs.setup.outputs.build_date }}
      build_type: ${{ needs.setup.outputs.build_type }}
    secrets: inherit

  build-lineage-sm6125:
    needs: setup
    uses: ./.github/workflows/lineage-sm6125.yml
    with:
      build_date: ${{ needs.setup.outputs.build_date }}
      build_type: ${{ needs.setup.outputs.build_type }}
    secrets: inherit

  build-crdroid-sm6150:
    needs: setup
    uses: ./.github/workflows/crdroid-sm6150.yml
    with:
      build_date: ${{ needs.setup.outputs.build_date }}
      build_type: ${{ needs.setup.outputs.build_type }}
    secrets: inherit
  
  build-pixelos-sm6150:
    needs: setup
    uses: ./.github/workflows/pixelos-sm6150.yml
    with:
      build_date: ${{ needs.setup.outputs.build_date }}
      build_type: ${{ needs.setup.outputs.build_type }}
    secrets: inherit

  build-awaken-sm6150:
    needs: setup
    uses: ./.github/workflows/awaken-sm6150.yml
    with:
      build_date: ${{ needs.setup.outputs.build_date }}
      build_type: ${{ needs.setup.outputs.build_type }}
    secrets: inherit

  build-mithorium-msm8937:
    needs: setup
    uses: ./.github/workflows/mithorium-msm8937.yml
    with:
      build_date: ${{ needs.setup.outputs.build_date }}
      build_type: ${{ needs.setup.outputs.build_type }}
    secrets: inherit

  release:
    # gotta add these later
    needs: [setup, build-lineage-sm6150, build-lineage-sm6125, build-crdroid-sm6150, build-pixelos-sm6150, build-awaken-sm6150, build-mithorium-msm8937]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./artifacts

      - name: List downloaded zips
        run: ls -lah artifacts

      - name: Extract Release Info
        id: info
        run: |
          INFO_FILE=$(find ./artifacts -path "*zako*" -name "release_info.txt" | head -n 1)
          if [ -z "$INFO_FILE" ]; then
            INFO_FILE=$(find ./artifacts -name "release_info.txt" | head -n 1)
          fi
          if [ -n "$INFO_FILE" ] && [ -f "$INFO_FILE" ]; then
            cat "$INFO_FILE" >> $GITHUB_OUTPUT
            echo "Loaded versions from $INFO_FILE!"
          else
            echo "KSU_NAME=Unknown" >> $GITHUB_OUTPUT
            echo "KSU_CODE=Unknown" >> $GITHUB_OUTPUT
            echo "SUSFS_VER=Unknown" >> $GITHUB_OUTPUT
            echo "BBG_VER=Unknown" >> $GITHUB_OUTPUT
            echo "NOMOUNT_VER=Unknown" >> $GITHUB_OUTPUT
          fi

      - name: Create Release and Upload builds
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: kernel-release-${{ needs.setup.outputs.timestamp }}
          name: Build ${{ needs.setup.outputs.fancy_date }}
          draft: false
          prerelease: false
          body: |
            > [!NOTE]   
            > - KSU Version: ${{ steps.info.outputs.KSU_NAME }} (${{ steps.info.outputs.KSU_CODE }})   
            > - SuSFS Version: ${{ steps.info.outputs.SUSFS_VER }}   
            > - Baseband Guard Version: ${{ steps.info.outputs.BBG_VER }}   
            > - Nomount Version: ${{ steps.info.outputs.NOMOUNT_VER }}   
               
            > [!IMPORTANT]
            > - The feature set can be seen in [here](https://github.com/riarumoda/perf_neon-builder#features).   
            > - The compatibility list can be seen in [here](https://github.com/riarumoda/perf_neon-builder#compatibility).   
            > - The installation steps can be seen in [here](https://github.com/riarumoda/perf_neon-builder#installation).   

            > [!CAUTION]   
            > - Always backup your boot and dtbo image first before proceeding!   
          files: artifacts/**/*.zip
          overwrite_files: true